version: '3'
services:
  postgres:
    container_name: simple-bank-db
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: simple_bank_db
        POSTGRES_ROOT_PASSWORD: postgres
        POSTGRES_ROOT_HOST: '%'
        POSTGRES_PORT: 5434
    ports:
        - "5434:5432"
    volumes:
        - ./db:/var/lib/postgresql/data
